# Generated by Django 5.0 on 2024-01-10 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 8, 30, 25, 763343, tzinfo=datetime.timezone.utc), verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='choice',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 8, 30, 25, 763359, tzinfo=datetime.timezone.utc), verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 8, 30, 25, 755306, tzinfo=datetime.timezone.utc), verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 8, 30, 25, 755324, tzinfo=datetime.timezone.utc), verbose_name='updated at'),
        ),
    ]
