# Generated by Django 5.0 on 2024-01-10 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_choice_created_at_alter_choice_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='choice',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 8, 39, 21, 239651, tzinfo=datetime.timezone.utc), verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 8, 39, 21, 239667, tzinfo=datetime.timezone.utc), verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 8, 39, 21, 231362, tzinfo=datetime.timezone.utc), verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 8, 39, 21, 231381, tzinfo=datetime.timezone.utc), verbose_name='updated at'),
        ),
    ]
