# Generated by Django 5.0 on 2024-01-10 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_choice_created_at_alter_choice_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('Categoria 1', 'Pregunta directa'), ('Categoria 2', 'Pregunta picante'), ('Categoria 3', 'Pregunta incomoda')], default='Categoria 1', max_length=20),
        ),
        migrations.AlterField(
            model_name='choice',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 8, 51, 11, 671275, tzinfo=datetime.timezone.utc), verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 8, 51, 11, 671295, tzinfo=datetime.timezone.utc), verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 8, 51, 11, 662947, tzinfo=datetime.timezone.utc), verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 8, 51, 11, 662966, tzinfo=datetime.timezone.utc), verbose_name='updated at'),
        ),
    ]
