# Generated by Django 5.0 on 2024-01-10 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_choice_created_at_alter_choice_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 9, 0, 45, 91438, tzinfo=datetime.timezone.utc), verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 9, 0, 45, 91456, tzinfo=datetime.timezone.utc), verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 9, 0, 45, 83387, tzinfo=datetime.timezone.utc), verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 9, 0, 45, 83404, tzinfo=datetime.timezone.utc), verbose_name='updated at'),
        ),
    ]
