# Generated by Django 4.2.8 on 2024-01-24 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_question_pollster_alter_choice_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pollster',
            new_name='pollsters',
        ),
        migrations.AlterField(
            model_name='choice',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 8, 21, 35, 274950, tzinfo=datetime.timezone.utc), verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 8, 21, 35, 274960, tzinfo=datetime.timezone.utc), verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 8, 21, 35, 274575, tzinfo=datetime.timezone.utc), verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 8, 21, 35, 274587, tzinfo=datetime.timezone.utc), verbose_name='updated at'),
        ),
    ]
