# Generated by Django 4.2.8 on 2024-01-24 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_rename_pollster_question_pollsters_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pollsters',
            new_name='pollster',
        ),
        migrations.AlterField(
            model_name='choice',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 8, 24, 26, 527988, tzinfo=datetime.timezone.utc), verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 8, 24, 26, 527998, tzinfo=datetime.timezone.utc), verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 8, 24, 26, 527598, tzinfo=datetime.timezone.utc), verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 8, 24, 26, 527610, tzinfo=datetime.timezone.utc), verbose_name='updated at'),
        ),
    ]
